import type { Metadata } from "next";
import { TopNav } from "../../components/marketing/TopNav";

export const metadata: Metadata = {
  title: "Legal | GitaGPT Mentor",
  description:
    "Privacy policy, terms of use, and legal disclaimers for GitaGPT Mentor.",
  alternates: { canonical: "https://gitagpt.tech/legal" },
};

const sections = [
  {
    id: "privacy",
    title: "Privacy Policy",
    intro:
      "We respect user privacy and design GitaGPT Mentor with minimal, responsible data handling.",
    items: [
      "We do not intentionally store sensitive conversations permanently.",
      "AI responses may be processed through third-party AI providers (e.g. Groq, Google, Modal) solely to generate guidance.",
      "We use privacy-respecting analytics to improve performance, usability, and product quality.",
      "We continuously refine safeguards to keep guidance respectful and trustworthy.",
      "No personal data is sold or shared with advertisers.",
      "You may request deletion of your account and data by contacting us directly.",
    ],
  },
  {
    id: "terms",
    title: "Terms of Use",
    intro:
      "By using GitaGPT Mentor, you agree to the following terms governing the service.",
    items: [
      "GitaGPT provides spiritual and informational guidance only.",
      "It does not provide medical, legal, financial, or professional advice.",
      "Users are responsible for decisions and actions they take based on guidance received.",
      "Service features, behavior, and availability may change as the platform evolves.",
      "Abusive, harmful, or automated misuse of the service is prohibited.",
      "We reserve the right to suspend access for violations of these terms.",
    ],
  },
  {
    id: "disclaimer",
    title: "Disclaimer",
    intro:
      "GitaGPT Mentor is an AI-powered tool and should be used with informed discretion.",
    items: [
      "All guidance is generated by AI models and may not be perfect, complete, or applicable to every situation.",
      "Responses are inspired by Bhagavad Gita teachings but do not represent any official religious authority.",
      "GitaGPT is not a substitute for professional counseling, therapy, or medical treatment.",
      "In critical or emergency situations, please contact appropriate professional services immediately.",
      "The creators and maintainers of GitaGPT are not liable for any outcomes resulting from use of this service.",
    ],
  },
];

export default function LegalPage() {
  return (
    <main className="relative min-h-screen bg-background text-foreground">
      <TopNav />

      {/* Background gradients */}
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_10%,rgba(255,215,0,0.12),transparent_35%),radial-gradient(circle_at_88%_80%,rgba(88,120,255,0.18),transparent_40%),linear-gradient(145deg,#05081c,#0a1740_38%,#201545_68%,#060718_100%)]" />

      <section className="relative mx-auto max-w-5xl px-6 pb-24 pt-14 sm:px-8">
        {/* Page header */}
        <p className="text-xs uppercase tracking-[0.24em] text-accent/90">
          Legal Information
        </p>
        <h1 className="mt-3 text-4xl font-semibold font-[var(--font-heading)] sm:text-5xl">
          Legal
        </h1>
        <p className="mt-4 max-w-3xl text-base leading-8 text-muted-foreground">
          Transparency, trust, and responsible AI — everything you need to know
          about using GitaGPT Mentor.
        </p>

        {/* Quick‑jump navigation */}
        <nav className="mt-8 flex flex-wrap gap-3">
          {sections.map((s) => (
            <a
              key={s.id}
              href={`#${s.id}`}
              className="inline-flex items-center rounded-xl border border-border/80 bg-background/45 px-4 py-2 text-sm font-medium transition hover:border-accent/40 hover:text-accent"
            >
              {s.title}
            </a>
          ))}
        </nav>

        {/* Sections */}
        <div className="mt-12 flex flex-col gap-8">
          {sections.map((section) => (
            <article
              key={section.id}
              id={section.id}
              className="group rounded-3xl border border-border/70 bg-card/55 p-8 backdrop-blur-md transition duration-500 hover:border-accent/35 hover:shadow-[0_8px_32px_rgba(255,215,0,0.06)] sm:p-10"
            >
              <h2 className="text-3xl font-semibold font-[var(--font-heading)] sm:text-4xl">
                {section.title}
              </h2>
              <p className="mt-5 text-base leading-8 text-muted-foreground">
                {section.intro}
              </p>
              <ul className="mt-6 space-y-3 text-sm leading-7 text-muted-foreground">
                {section.items.map((item) => (
                  <li
                    key={item}
                    className="flex items-start gap-3 before:mt-[0.45rem] before:inline-block before:h-1.5 before:w-1.5 before:shrink-0 before:rounded-full before:bg-accent/60"
                  >
                    {item}
                  </li>
                ))}
              </ul>
            </article>
          ))}
        </div>

        {/* Last‑updated note */}
        <p className="mt-10 text-xs text-muted-foreground/60">
          Last updated: April 2026
        </p>
      </section>
    </main>
  );
}
